version: "3.8"


services:
  fastapp:
    build: ./fastapp
    image: fastapp
    container_name: fastapp
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ./fastapp:/code
    ports:
      - 8000:80

  dollop:
    build: ./dollop
    image: dollop
    container_name: dollop
    command: yarn dev
    volumes:
      - ./dollop:/usr/app
      - ./dollop/node_modules:/usr/app/node_modules
    ports:
      - 3000:80
    environment:
      PORT: 80

  glimmer:
    build: ./glimmer
    image: glimmer
    container_name: glimmer
    command: yarn dev
    volumes:
      - ./glimmer:/usr/app
      - ./glimmer/node_modules:/usr/app/node_modules
    ports:
      - 3001:80
    environment:
      PORT: 80

  nginx:
    image: nginx:1.19
    container_name: spoon-proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - fastapp:fastapp
      - dollop:dollop

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: spoon-rabbitmq
    volumes:
      - rabbitmq_etc:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672


volumes:
  rabbitmq_etc:
  rabbitmq_data:
  rabbitmq_logs:
