version: "3.8"


services:
  fastapp:
    build: ./fastapp
    image: fastapp
    container_name: fastapp
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ./fastapp:/code
    ports:
      - 8000:80

  dollop:
    build: ./dollop
    image: dollop
    container_name: dollop
    command: yarn dev
    volumes:
      - ./dollop:/usr/src/app
      - node-modules-dollop:/usr/src/app/node_modules
    ports:
      - 3000:80
    environment:
      PORT: 80

  nginx:
    build: ./proxy
    image: nginx:1.19
    container_name: spoon-proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    links:
      - fastapp:fastapp
      - dollop:dollop

volumes:
  node-modules-dollop:
